### ISSUE TITLE
add website link to readme

### ISSUE THREAD

**Issue by ManDude** [open-goal/open-goal.github.io#118]
nitpick

**Comment by xTVaser** [comment]
![image](https://user-images.githubusercontent.com/13153231/220233872-2082a7b1-124a-485c-a4c6-4081097ec31b.png)
github pages repos do automatically have a link (assuming it's not a refined github feature)

**Comment by ManDude** [comment]
I meant opengoal.dev, but I don't even see that icon anyway for some reason.
