### ISSUE TITLE
FAQ link on game versions is broken

### ISSUE THREAD

**Issue by Calinou** [open-goal/open-goal.github.io#148]
https://opengoal.dev/docs/faq/:

> We support all retail versions of the original Jak and Daxter. For more details on how your version of the games matter, see [this page](https://opengoal.dev/docs/faq/usage/game_versions).

On Firefox 112, "this page" points to `https://opengoal.dev/docs/faq/usage/game_versions`, but it should point to `https://opengoal.dev/docs/usage/game_versions`.

**Comment by ManDude** [comment]
Weirdly enough it does point to the correct page.
