### ISSUE TITLE
search feature is broken

### ISSUE THREAD

**Issue by ManDude** [open-goal/open-goal.github.io#151]
A lot of page results from the search feature don't point to the right page. For example:

![image](https://github.com/open-goal/open-goal.github.io/assets/7569514/3923978f-7a87-44ba-aaaa-eba91a9e3307)

goes to https://opengoal.dev/docs/developing/registers/ instead of  https://opengoal.dev/docs/porting-info/registers

**Comment by xTVaser** [comment]
This has been fixed, the crawler was unable to crawl the site because our domain changed. Also https://github.com/open-goal/open-goal.github.io/pull/160 should prevent the source docs from flooding the search results
