### ISSUE TITLE
The "Getting started" button seems to not function

### ISSUE THREAD

**Issue by yodaxtah** [open-goal/open-goal.github.io#233]
I noticed the "Getting started" button doesn't do anything, or so it seems.

![image](https://github.com/open-goal/open-goal.github.io/assets/159531413/400c3348-322e-4ce5-a458-ddf4512cadc1)

I expect it to take me to the [installation documentation page](https://opengoal.dev/docs/usage/installation/) perhaps, but when clicking it now, nothing seems to process the click. I suppose it's not intended. I checked both on Firefox and Ungoogled-chromium.

Nice work on the website btw. Haven't encountered any `c is not a function` since the renewal.

**Comment by yodaxtah** [comment]
Okay, so the button is in [src/components/LauncherDownloadLink/index.js](https://github.com/open-goal/open-goal.github.io/blob/022b7b5448e6153780f668ca7c184d17bf5191ee/src/components/LauncherDownloadLink/index.js#L171). I'll have a further look.

**Comment by xTVaser** [comment]
yup you're right, just missed it
